
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENTESIS_DERECHO = 11;
  public static final int RESERVADA_PROGRAM = 15;
  public static final int RESERVADA_MODA = 28;
  public static final int PARENTESIS_IZQUIERDO = 10;
  public static final int PUNTO_Y_COMA = 9;
  public static final int NUMEROS = 48;
  public static final int RESERVADA_END = 16;
  public static final int DOS_PUNTOS = 3;
  public static final int RESERVADA_EJEY_GRAFICA = 41;
  public static final int CORCHETE_DERECHO = 13;
  public static final int RESERVADA_MAX = 30;
  public static final int SIGNO_IGUAL = 14;
  public static final int RESERVADA_VAR = 17;
  public static final int RESERVADA_GRAFICA_PIE = 36;
  public static final int RESERVADA_TITULOX_GRAFICA = 42;
  public static final int RESERVADA_GRAFIA_HISTOGRAMA = 38;
  public static final int RESRVADA_LABEL_GRAFICA = 45;
  public static final int RESERVADA_EXEC = 46;
  public static final int GUION = 6;
  public static final int CORCHETE_IZQUIERDO = 12;
  public static final int ID = 2;
  public static final int RESERVADA_CONSOLE = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int RESERVADA_CHAR = 19;
  public static final int MAYOR_QUE = 5;
  public static final int RESERVADA_MEDIA = 26;
  public static final int RESERVADA_DOUBLE = 18;
  public static final int RESERVADA_PRINT = 33;
  public static final int RESERVADA_VALUES_GRAFICA = 44;
  public static final int PUNTO = 7;
  public static final int RESERVADA_TITULOY_GRAFICA = 43;
  public static final int RESERVADA_COLUMN = 34;
  public static final int RESERVADA_MIN = 31;
  public static final int RESERVADA_MULTIPLICACION = 23;
  public static final int RESERVADA_EJEX_GRAFICA = 40;
  public static final int RESERVADA_GRAFICA_BARRA = 35;
  public static final int STRING = 47;
  public static final int RESERVADA_VARIANZA = 29;
  public static final int MENOR_QUE = 4;
  public static final int RESERVADA_RESTA = 22;
  public static final int RESERVADA_SUMA = 21;
  public static final int RESERVADA_TITULO_GRAFICA = 39;
  public static final int RESERVADA_ARRAY = 20;
  public static final int RESERVADA_MEDIANA = 27;
  public static final int RESERVADA_DIVISION = 24;
  public static final int RESERVADA_MODULO = 25;
  public static final int RESERVADA_GRAFICA_LINE = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "DOS_PUNTOS",
  "MENOR_QUE",
  "MAYOR_QUE",
  "GUION",
  "PUNTO",
  "COMA",
  "PUNTO_Y_COMA",
  "PARENTESIS_IZQUIERDO",
  "PARENTESIS_DERECHO",
  "CORCHETE_IZQUIERDO",
  "CORCHETE_DERECHO",
  "SIGNO_IGUAL",
  "RESERVADA_PROGRAM",
  "RESERVADA_END",
  "RESERVADA_VAR",
  "RESERVADA_DOUBLE",
  "RESERVADA_CHAR",
  "RESERVADA_ARRAY",
  "RESERVADA_SUMA",
  "RESERVADA_RESTA",
  "RESERVADA_MULTIPLICACION",
  "RESERVADA_DIVISION",
  "RESERVADA_MODULO",
  "RESERVADA_MEDIA",
  "RESERVADA_MEDIANA",
  "RESERVADA_MODA",
  "RESERVADA_VARIANZA",
  "RESERVADA_MAX",
  "RESERVADA_MIN",
  "RESERVADA_CONSOLE",
  "RESERVADA_PRINT",
  "RESERVADA_COLUMN",
  "RESERVADA_GRAFICA_BARRA",
  "RESERVADA_GRAFICA_PIE",
  "RESERVADA_GRAFICA_LINE",
  "RESERVADA_GRAFIA_HISTOGRAMA",
  "RESERVADA_TITULO_GRAFICA",
  "RESERVADA_EJEX_GRAFICA",
  "RESERVADA_EJEY_GRAFICA",
  "RESERVADA_TITULOX_GRAFICA",
  "RESERVADA_TITULOY_GRAFICA",
  "RESERVADA_VALUES_GRAFICA",
  "RESRVADA_LABEL_GRAFICA",
  "RESERVADA_EXEC",
  "STRING",
  "NUMEROS"
  };
}

